### ISSUE TITLE
Errors in compose view with modern django

### ISSUE THREAD

**Issue by savelmtr** [arneb/django-messages#136]
When I tried to test compose page, I've got an error: `render() got an unexpected keyword argument 'renderer'`
So, full code of error is here: https://pastebin.com/puZiBriw
I've discovered this problem may connected with the version of Django, for example, [here](https://groups.google.com/forum/#!msg/django-users/odBVju946ng/-ZHsDNTsAwAJ) people solving the same case. But in this case I couldn't solve the problem by just adding `, renderer=None` to the _compose_ view.
We should do something with this thing, I think, do we?

**Comment by savelmtr** [comment]
So, guys, I've solve this problem.
We just need to update the _fields.py_ like this:
old:
`18:    def render(self, name, value, attrs=None):
23:        return super(CommaSeparatedUserInput, self).render(name, value, attrs)`
new:
`18:    def render(self, name, value, attrs=None, renderer=None):
23:        return super(CommaSeparatedUserInput, self).render(name, value, attrs, renderer)`

**Comment by arneb** [comment]
Thanks for reporting the Issue! The fix looks good too.

**Comment by believeohiozua** [comment]
@arneb please where do I find the fix because am having the same error right now.
do replay thanks.


`

Request Method: | GET
-- | --
http://127.0.0.1:8000/messages/compose/
2.2.4
TypeError
render() got an unexpected keyword argument 'renderer'
C:\Users\MrBIG\Envs\arena\lib\site-packages\django\forms\boundfield.py in as_widget, line 93
C:\Users\MrBIG\Envs\arena\Scripts\python.exe
3.7.3
['C:\\Windows.old.000\\Users\\believeohiozua\\Downloads\\WEBAPPS\\talesarena',  'C:\\Users\\MrBIG\\Envs\\arena\\Scripts\\python37.zip',  'C:\\Users\\MrBIG\\Envs\\arena\\DLLs',  'C:\\Users\\MrBIG\\Envs\\arena\\lib',  'C:\\Users\\MrBIG\\Envs\\arena\\Scripts',  'c:\\users\\mrbig\\appdata\\local\\continuum\\anaconda3\\Lib',  'c:\\users\\mrbig\\appdata\\local\\continuum\\anaconda3\\DLLs',  'C:\\Users\\MrBIG\\Envs\\arena',  'C:\\Users\\MrBIG\\Envs\\arena\\lib\\site-packages']
Mon, 2 Dec 2019 10:07:34 +0000

`

**Comment by arneb** [comment]
@savelmtr can you please check with current master branch? this should have been fixed already ...

**Comment by savelmtr** [comment]
@arneb Yes, it's been fixed. But, maybe, we shall update this package in pip.
