### ISSUE TITLE
Why extends base.html in django_messages/base.html

### ISSUE THREAD

**Issue by viciousstar** [arneb/django-messages#62]
I use python3 and django1.8,and install django_messages.
I did not change anything when I add django_messages in INSTALL_APP in settings.py.
Then when I access /messages, I meet a problem just like http://stackoverflow.com/questions/31458813/templatenotfound-after-installing-django-messages-and-django-postman .
If I comment the first line

```
{% extends "base.html" %}
```

in django_messages/base.html or add a my owner file base.html, both are worked.
Just like the title saying, Why?

**Comment by arneb** [comment]
Because it is not possible to provide a set of templates which fit every site that wants to integrate django-messages.

The included templates are examples, to get an idea, how to build your own stuff.

The templates wouldn't make any more sense when not extending base.html, because they would still look shitty and would not integrate with your site (e.g. no navigation).

Removing the extends line would remove some confusion and I will consider it for the future.

**Comment by viciousstar** [comment]
Oh, I see. It is just a examples for templates inheritance.I do not think it is a good idea when the user must modify the source code or is forced to create a new base.html to run ti successfully, even it is a good design pattern of templates.
Thinks.
