### ISSUE TITLE
User to User Email via App

### ISSUE THREAD

**Issue by HenryMehta** [arneb/django-messages#87]
I know this is not an issue and I apologise for using this method to ask a question but I'm interested if you've considered extending the app to enable User to User email via the app, hiding the users' emails from each other.  And how difficult do you think this extension would be?

**Comment by arneb** [comment]
The feature you're describing was planned in the beginning. Then it became clear, that there is no generic way to receive the response emails, because email setups may vary a lot between environments.

Nevertheless there is nothing in django_messages that hinders you from implementing it in your project. django_messages already sends out email to the recipients, when a new message is created ("received"). So when every you receives an response-email (maybe polling an imap inbox) just create a Message Object an save it.

Btw. you can fully customize the outgoing emails via template overrides (e.g. adding a note that the user may reply via email).

**Comment by HenryMehta** [comment]
Thank you; so in your opinion I should be able to integrate with django-mailbox relatively easily?

**Comment by arneb** [comment]
Yes, django-mailbox makes it easy to receive emails and it doesn't make sense to duplicate this in django-messages.

django-mailbox sends a signal everytime a new message is received and you can hook on to this. Something along the following lines should get you started. The hard part is to figure out to which message the email belongs (see code comments below).

```python
from django import dispatch
from django.contrib.auth import get_user_model
from django_mailbox.signals import message_received
from django_messages.models import Message
User = get_user_model()

@dispatch.receiver(message_received)
def process_mail(sender, message, **kwargs):
    # Implement 'is_reply_to' function that figures out to
    # which message this is a reply. message.in_reply_to and
    # message.to_address are some starting points.
    parent = is_reply_to(message)
    data = {
        'body': message.body,
        'subject': message.subject,
        'recipient': parent.sender,
        'parent_msg': parent
    }
    # figure out who's the sender, maybe just trust the email:
    try:
        data['sender'] = User.objects.get(email=message.from_address[0])
    except:
        # no user with the email address found, handle it
    Message.objects.create(**data)
    # once the Message object is created the recipient will automatically get a
    # notification email with the received message.
```

**Comment by HenryMehta** [comment]
Thank you
